# Generated by Django 4.0.4 on 2022-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rent_per_day',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
